### ISSUE TITLE
Create the getLedgers endpoint

### ISSUE THREAD

**Issue by L-Zuluaga** [kommitters/soroban.ex#161]
ℹ️ This issue is part of Epic #158 

## Objective

![image](https://github.com/user-attachments/assets/69c40f95-c9e8-4fcc-89b9-51cd39af113c)
It’s required to create the getLedgers endpoint in the [s](https://github.com/kommitters/soroban.ex/tree/main/lib/rpc/endpoints)[oroban.ex](https://github.com/kommitters/soroban.ex/tree/main/lib/rpc/endpoints) repo. The info about the endpoint specification can be found in the [soroban-rpc](https://github.com/stellar/soroban-rpc) repo.

https://github.com/kommitters/soroban.ex/tree/main/lib/rpc/endpoints
https://github.com/stellar/soroban-rpc/issues/111

## Checklist

- [ ]  Add the logic for the endpoint
- [ ]  Add the respective tests
- [ ]  Update the readme

**Comment by einerzg** [comment]
Currently, the getLedgers endpoint is not available.

The following issue should be followed up: https://github.com/stellar/soroban-rpc/issues/111
